### ISSUE TITLE
how to get the Test-Driven-Development ansible roles using molecule to work?

### ISSUE THREAD

**Issue by thepenguinthatwants** [nfisher23/some-ansible-examples#1]
Hi Nickolas!

I've tried to run your molecule role based on https://nickolasfisher.com/blog/How-to-do-Test-Driven-Development-on-Your-Ansible-Roles-Using-Molecule

by molecule create command I got.    

TASK [Create molecule instance(s)] *********************************************
    failed: [localhost] (item=instance) => {"ansible_loop_var": "item", "changed": false, "item": {"box": "ubuntu/xenial64", "memory": 2048, "name": "instance", "provider_raw_config_args": ["customize ['modifyvm', :id, '--uartmode1', 'disconnected']"]}, "module_stderr": "ERROR: Driver missing, install python-vagrant.\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}

Did I miss something? Does it need some steps before it works?

**Comment by nfisher23** [comment]
Hey, sorry for the late reply. If you take a look at the error message, it looks like you need to install `python-vagrant` on your host machine in this case.

In the future, you can see verbose outputs to problems like this with `molecule --debug *command*`, that will give you a lot more information to work with.

**Comment by thepenguinthatwants** [comment]
Thanks for answering. I guess this could easily be ported to use docker?
